import type { Metadata } from 'next';
import './globals.css';
export const metadata: Metadata = {
  title: 'Rebuild IT',
  description: 'Generated by Onlook'
};
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en">
            <body className="">{children}</body>
        </html>;
}
